config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :doctors
  root to: 'visitors#index'
  devise_for :users
  resources :users

  get '/listings' => "posts#index"

end

app/models/certification.rb
class Certification < ActiveRecord::Base
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :certifications
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/recruiter.rb
class Recruiter < User
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin, :doctor, :recruiter]
  after_initialize :set_default_role, :if => :new_record?
  has_many :posts
  has_many :certifications
  #has_attached_file :profile_picture, default_url: "assets/images/prof.png"

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :full_name, :title, :education, :specialty, :target_salary, :profile_picture, :resume, :role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :full_name, :title, :education, :specialty, :target_salary, :profile_picture, :resume, :role])
  end

end

app/controllers/certification_controller.rb
class CertificationController < ApplicationController
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:title, :full_name, :education, :specialty, :target_salary, :certifications_id, :profile_picture, :resume)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :short_name, :hospital, :body, :related_posts, :offering_salary, :location, :owner_id)
    end
end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
  def new
  end

  def show
  end

  def create
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/linkedin'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(secure_params)
    @user.save
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end


  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:full_name, :title, :edcuation,:specialty, :target_salary, :profile_picture, :resume, :role)
  end



end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certification_helper.rb
module CertificationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :education %><br>
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :specialty %><br>
    <%= f.text_field :specialty %>
  </div>
  <div class="field">
    <%= f.label :target_salary %><br>
    <%= f.text_field :target_salary %>
  </div>
  <div class="field">
    <%= f.label :certifications_id %><br>
    <%= f.text_field :certifications_id %>
  </div>
  <div class="field">
    <%= f.label :profile_picture %><br>
    <%= f.text_field :profile_picture %>
  </div>
  <div class="field">
    <%= f.label :resume %><br>
    <%= f.text_field :resume %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/create.html.erb
<h1>Doctors#create</h1>
<p>Find me in app/views/doctors/create.html.erb</p>

app/views/doctors/destroy.html.erb
<h1>Doctors#destroy</h1>
<p>Find me in app/views/doctors/destroy.html.erb</p>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Full name</th>
      <th>Education</th>
      <th>Specialty</th>
      <th>Target salary</th>
      <th>Certifications</th>
      <th>Profile picture</th>
      <th>Resume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.title %></td>
        <td><%= doctor.full_name %></td>
        <td><%= doctor.education %></td>
        <td><%= doctor.specialty %></td>
        <td><%= doctor.target_salary %></td>
        <td><%= doctor.certifications %></td>
        <td><%= doctor.profile_picture %></td>
        <td><%= doctor.resume %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/registration.html.erb
<h2>Sign up</h2>

<%= simple_form_for(@doctor, url: registration_path(@doctor), html: {multipart:true, action:}),  do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.input :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @doctor.title %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @doctor.full_name %>
</p>

<p>
  <strong>Education:</strong>
  <%= @doctor.education %>
</p>

<p>
  <strong>Specialty:</strong>
  <%= @doctor.specialty %>
</p>

<p>
  <strong>Target salary:</strong>
  <%= @doctor.target_salary %>
</p>

<p>
  <strong>Certifications:</strong>
  <%= @doctor.certifications %>
</p>

<p>
  <strong>Profile picture:</strong>
  <%= @doctor.profile_picture %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @doctor.resume %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li class='nav-item'><%= link_to 'Users', users_path, class: 'nav-link' %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container" style="padding-left:0;margin-left:0;padding-right:0;margin-right:0;width:100%">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <a class="navbar-brand topnav" href="/">MDirectory</a>
      </li>
      <%= render 'layouts/navigation_links' %>
      <%= render 'layouts/nav_links_for_auth' %>
    </ul>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Experimental" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Experimental" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= stylesheet_link_tag 'landing-page' %>
    <%= stylesheet_link_tag 'signin' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <main role="main" style="margin-top:0;width:100%;padding-left:0;padding-right:0;">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>



  </body>
  <footer style="position:relative;bottom:0;padding-top:10px;width:100%;text-align:center">
      <div class="container" style="display:inline-block">
          <div class="row">
              <div class="col-lg-12">
                  <a href="/">Home</a>&sdot;<a href="/about">About</a>
                  <p class="copyright text-muted small">Copyright &copy; MDirectory 2016. All Rights Reserved</p>
              </div>
          </div>
      </div>
  </footer>
</html>

app/views/pages/about.html.erb
Thing

app/views/posts/_form.html.erb
<%= simple_form_for(@post, :controller => "posts#index") do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :hospital %>
    <%= f.input :body %>
    <%= f.input :offering_salary %>
    <%= f.input :location %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Standing Contracts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Hospital</th>
      <th>Offering salary</th>
      <th>Location</th
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= post.hospital %></td>
        <td>&#36;<%= number_with_delimiter(post.offering_salary, :delimiter => ',') %></td>
        <td><%= post.location %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, class:"btn btn-default", style:"text-align:center;" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="form-signin">
  <%= render 'form' %>
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @post.hospital %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Offering salary:</strong>
  <%= @post.offering_salary %>
</p>

<p>
  <strong>Location:</strong>
  <%= @post.location %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/recruiters/create.html.erb
<h1>Recruiters#create</h1>
<p>Find me in app/views/recruiters/create.html.erb</p>

app/views/recruiters/destroy.html.erb
<h1>Recruiters#destroy</h1>
<p>Find me in app/views/recruiters/destroy.html.erb</p>

app/views/recruiters/new.html.erb
<h1>Recruiters#new</h1>
<p>Find me in app/views/recruiters/new.html.erb</p>

app/views/recruiters/show.html.erb
<h1>Recruiters#show</h1>
<p>Find me in app/views/recruiters/show.html.erb</p>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/visitors/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>MDirectory - Demo</title>

    <!-- Bootstrap Core CSS -->
    <% stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" %>

    <!-- Custom CSS -->
    <% stylesheet_link_tag "landing-page" %>

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

</head>

<body>
    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>MDirectory</h1>
                        <h3>Connecting Doctors with Those in Need</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li><%= link_to "I'm a doctor", user_registration_path, :class => "btn btn-default btn-lg", :params => "doctor" %></li>
                            <li><%= link_to "I'm a recruiter", user_registration_path, :class => "btn btn-default btn-lg", :params => "recruiter" %></li>
                            <li><%= link_to "View Listings", '/listings', :class => "btn btn-default btn-lg" %></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/visitors/show.html.erb
<%= image_tag(@user.profile_picture, size:100) %>
<%= @user.full_name %>
<%= @user.email %>